

name: Build
on: [push, pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: linux-x64
        path: ./out
